spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/bizzcart_user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sumit
    password: sumit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: DEBUG
